### ISSUE TITLE
indentity.ic0.app hangs in an endless loop on Mobile Safari and constantly reloads the page

### ISSUE THREAD

**Issue by plitzenberger** [dfinity/agent-js#453]
<img width="1332" alt="Screenshot 2021-05-11 at 11 38 28" src="https://user-images.githubusercontent.com/2835032/117794465-8d6eb200-b24d-11eb-95ad-47b2a7195950.png">

![IMG_2185](https://user-images.githubusercontent.com/2835032/117793241-53e97700-b24c-11eb-947e-056a193cec1f.PNG)

**Comment by roman-kashitsyn** [comment]
I believe the issue here is caused by a failure in the service worker that is hard to observe directly.
I managed to reproduce this problem on an old iPad mini running iOS 12.5.4 (Safari 12). In my case, the issue seems to be related to the [lack of BigInt support in Safari ≤ 14](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt).
This is the error I get in the service worker code:
```
Unhandled Promise Rejection: ReferenceError: Can't find variable: BigInt
```
The service worker fails in the background, the actual resource is not fetched, and the SW loading page keeps refreshing itself.
